### ISSUE TITLE
Exception if PLANDATE data is not present

### ISSUE THREAD

**Issue by Tr1n0va** [marq24/ha-evcc#48]
### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

I dont know whats the problem, but i think it is one.

### Add your DEBUG log output

```shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/evcc_intg/__init__.py:374
Integration: evcc☀️🚘- Solar Charging (Dokumentation, Probleme)
Erstmals aufgetreten: 21:31:46 (16 Vorkommnisse)
Zuletzt protokolliert: 21:35:31

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/evcc_intg/sensor.py", line 76, in native_value
    value = self.coordinator.read_tag(self.tag, self.idx)
  File "/config/custom_components/evcc_intg/__init__.py", line 249, in read_tag
    ret = self.read_tag_loadpoint(tag=tag, loadpoint_idx=idx)
  File "/config/custom_components/evcc_intg/__init__.py", line 274, in read_tag_loadpoint
    value = self._convert_time(value)
  File "/config/custom_components/evcc_intg/__init__.py", line 374, in _convert_time
    value = value.replace("Z", "+00:00")
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by marq24** [comment]
please update to https://github.com/marq24/ha-evcc/releases/tag/2024.12.0 and close if sloved
